import { StyleSheet } from "react-native";
import COLORS from "@/assets/colors";
import TYPOGRAPHY from "@/assets/typography";

export const styles = StyleSheet.create({
  container: {
    flexDirection: "row",
    justifyContent: "space-between", // Changed from flex-start to space-between
    alignItems: "center",
    width: "100%", // Ensure container takes full width
    gap: 12,
  },
  btn: {
    position: "relative" as const,
    backgroundColor: COLORS.lighterBackground,
    height: 40,
    borderRadius: 24,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
    flex: 1, // Make buttons grow equally to fill space
    borderWidth: 1,
    borderColor: COLORS.borderDarkColor,
  },
  fullWidthBtn: {
    width: "100%",
  },
  text: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.size.xs,
    fontWeight: TYPOGRAPHY.fontWeightToString(TYPOGRAPHY.semiBold),
    textAlign: "center", // Ensure text is centered
  },
});

export const modalOverlayStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'flex-end',
    padding: 0,
  },
  drawerContainer: {
    backgroundColor: COLORS.lighterBackground,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    paddingTop: 16,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: COLORS.borderDarkColor,
    maxHeight: '100%',
    paddingHorizontal: 20,
  },
  title: {
    fontSize: TYPOGRAPHY.size.xl,
    fontWeight: 600,
    marginBottom: 16,
    textAlign: 'center',
    color: COLORS.white,
  },
  modeContainer: {
    marginBottom: 24,
    width: '100%',
  },
  sectionTitle: {
    fontWeight: 500,
    fontSize: TYPOGRAPHY.size.sm,
    marginBottom: 8,
    color: COLORS.white,
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    columnGap: 12,
    rowGap: 8,
    marginTop: 16,
    flexWrap: 'nowrap',
    paddingHorizontal: 0,
  },
  modeButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: COLORS.lightBackground,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
  },
  modeButtonText: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.size.md,
    fontWeight: TYPOGRAPHY.fontWeightToString(TYPOGRAPHY.medium),
  },
  selectedBtn: {
    backgroundColor: COLORS.lightGrey,
  },
  selectedBtnText: {
    color: COLORS.white,
    fontWeight: TYPOGRAPHY.fontWeightToString(TYPOGRAPHY.bold),
  },
  tierContainer: {
    marginBottom: 16,
  },
  tierButton: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: COLORS.lighterBackground,
    borderWidth: 1,
    borderColor: COLORS.borderDarkColor,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 30,
  },
  tierButtonText: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.size.xs,
    fontWeight: TYPOGRAPHY.fontWeightToString(TYPOGRAPHY.medium),
    textAlign: 'center',
  },
  inputContainer: {
    marginBottom: 16,
  },
  statusContainer: {
    backgroundColor: COLORS.darkerBackground,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 6,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.borderDarkColor,
  },
  statusText: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.size.sm,
    textAlign: 'center',
  },
  label: {
    fontWeight: 500,
    marginTop: 8,
    marginBottom: 8,
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.white,
  },
  input: {
    borderWidth: 1,
    borderColor: COLORS.borderDarkColor,
    borderRadius: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    fontSize: TYPOGRAPHY.size.sm,
    backgroundColor: COLORS.lighterBackground,
    color: COLORS.white,
  },
  inputError: {
    borderColor: COLORS.errorRed,
  },
  errorText: {
    color: COLORS.errorRed,
    fontSize: TYPOGRAPHY.size.xs,
    marginTop: 4,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 6,
    minHeight: 48,
    backgroundColor: COLORS.brandBlue,
  },
  modalButtonText: {
    color: COLORS.white,
    fontWeight: TYPOGRAPHY.fontWeightToString(TYPOGRAPHY.semiBold),
    fontSize: TYPOGRAPHY.size.md,
  },
  tierButtonRow: {
    flexDirection: 'row',
    width: '100%',
    columnGap: 8,
    rowGap: 10,
    flexWrap: 'nowrap',
  },
  presetButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  presetButton: {
    flex: 1,
    backgroundColor: COLORS.lightGrey,
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderRadius: 12,
    alignItems: 'center',
    marginHorizontal: 4,
  },
  presetButtonText: {
    color: COLORS.white,
    fontWeight: TYPOGRAPHY.fontWeightToString(TYPOGRAPHY.semiBold),
    fontSize: TYPOGRAPHY.size.md,
  },
  amountControlContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 56,
    borderRadius: 16,
    backgroundColor: COLORS.lightGrey,
    overflow: 'hidden',
  },
  controlButton: {
    width: 56,
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
  },
  controlButtonText: {
    fontSize: 24,
    color: COLORS.white,
    fontWeight: TYPOGRAPHY.fontWeightToString(TYPOGRAPHY.bold),
  },
  amountInput: {
    flex: 1,
    color: COLORS.white,
    fontWeight: TYPOGRAPHY.fontWeightToString(TYPOGRAPHY.bold),
    fontSize: 20,
    textAlign: 'center',
    height: '100%',
  },
  dragHandle: {
    width: 36,
    height: 5,
    backgroundColor: COLORS.borderDarkColor,
    borderRadius: 2.5,
    alignSelf: 'center',
    marginBottom: 16,
  },
  scrollContent: {
    paddingBottom: 20,
  },
  commissionContainer: {
    backgroundColor: COLORS.darkerBackground,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 6,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.borderDarkColor,
  },
  commissionText: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.size.xs,
    textAlign: 'center',
  },
  amountLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  maxButton: {
    backgroundColor: COLORS.lightGrey,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 28,
  },
  maxButtonText: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.size.xs,
    fontWeight: TYPOGRAPHY.fontWeightToString(TYPOGRAPHY.semiBold),
  },
  tokenSelectorButton: {
    borderWidth: 1,
    borderColor: COLORS.borderDarkColor,
    borderRadius: 8,
    backgroundColor: COLORS.lighterBackground,
    padding: 12,
  },
  tokenSelectorContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  tokenIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    marginRight: 12,
  },
  tokenIconPlaceholder: {
    backgroundColor: COLORS.lightGrey,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tokenIconText: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.size.sm,
    fontWeight: TYPOGRAPHY.fontWeightToString(TYPOGRAPHY.bold),
  },
  tokenInfo: {
    flex: 1,
  },
  tokenSymbol: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.size.md,
    fontWeight: TYPOGRAPHY.fontWeightToString(TYPOGRAPHY.semiBold),
    marginBottom: 2,
  },
  tokenName: {
    color: COLORS.greyMid,
    fontSize: TYPOGRAPHY.size.sm,
    marginBottom: 2,
  },
  tokenBalance: {
    color: COLORS.greyMid,
    fontSize: TYPOGRAPHY.size.xs,
  },
  tokenRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.lightGrey,
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.borderDarkColor,
  },
  changeTokenButton: {
    backgroundColor: COLORS.brandBlue,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
  },
  changeTokenText: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.size.xs,
    fontWeight: TYPOGRAPHY.fontWeightToString(TYPOGRAPHY.semiBold),
  },
});
