import { StyleSheet, Dimensions, Platform, ImageStyle } from 'react-native';
import COLORS from '@/assets/colors';
import TYPOGRAPHY from '@/assets/typography';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  drawerContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: height * 0.85,
    paddingHorizontal: 16,
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
    shadowColor: COLORS.black,
    shadowOffset: {
      width: 0,
      height: -3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
  },
  dragHandleContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
  },
  dragHandle: {
    width: 40,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: COLORS.borderDarkColor,
  },
  drawerContent: {
    paddingBottom: 20,
  },
  drawerHeader: {
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderDarkColor,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.lighterBackground,
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: TYPOGRAPHY.size.lg,
    color: COLORS.white,
  },
  statValueText: {
    fontSize: TYPOGRAPHY.size.sm,
    fontWeight: TYPOGRAPHY.weights.bold,
    color: COLORS.white,
    flexShrink: 1,
    flexWrap: 'nowrap',
    textAlign: 'center',
  },
  tokenInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 16,
    paddingHorizontal: 8,
  },
  tokenImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
    backgroundColor: COLORS.lighterBackground,
    overflow: 'hidden',
  } as ImageStyle,
  nftImage: {
    width: 90,
    height: 90,
    borderRadius: 8,
    marginRight: 16,
    backgroundColor: COLORS.lighterBackground,
    overflow: 'hidden',
  } as ImageStyle,
  tokenNameContainer: {
    flex: 1,
  },
  tokenName: {
    fontSize: TYPOGRAPHY.size.xl,
    fontWeight: TYPOGRAPHY.weights.bold,
    color: COLORS.white,
    marginBottom: 4,
  },
  tokenSymbol: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textLight,
  },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  tokenPrice: {
    fontSize: TYPOGRAPHY.size.xl,
    fontWeight: TYPOGRAPHY.weights.bold,
    color: COLORS.white,
    marginRight: 8,
  },
  priceChange: {
    fontSize: TYPOGRAPHY.size.sm,
    fontWeight: TYPOGRAPHY.weights.medium,
  },
  tabContainer: {
    flexDirection: 'row',
    marginVertical: 16,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  activeTabButton: {
    borderBottomColor: COLORS.brandBlue,
  },
  tabText: {
    fontSize: TYPOGRAPHY.size.lg,
    color: COLORS.greyDark,
  },
  activeTabText: {
    color: COLORS.brandBlue,
    fontWeight: TYPOGRAPHY.weights.medium,
  },
  tabContent: {
    // Removed flex: 1 here as contentContainerStyle handles the growth
  },
  section: {
    marginBottom: 20,
    backgroundColor: COLORS.lightBackground,
    borderRadius: 12,
    padding: 16,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: TYPOGRAPHY.size.xl,
    fontWeight: TYPOGRAPHY.weights.semiBold,
    marginBottom: 12,
    color: COLORS.white,
  },
  sectionText: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textLight,
    lineHeight: TYPOGRAPHY.lineHeight.sm,
  },
  timeframeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 16,
    backgroundColor: COLORS.darkerBackground,
    borderRadius: 12,
    padding: 4,
  },
  timeframeButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  activeTimeframeButton: {
    backgroundColor: COLORS.lighterBackground,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  timeframeText: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.greyMid,
    fontWeight: '600',
  },
  activeTimeframeText: {
    color: COLORS.brandPrimary,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderDarkColor,
  },
  detailLabel: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textLight,
  },
  detailValue: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.white,
    fontWeight: TYPOGRAPHY.weights.medium,
    maxWidth: '60%',
    textAlign: 'right',
  },
  tokenStatsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  statItem: {
    width: '31%',
    backgroundColor: COLORS.lighterBackground,
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
  },
  statLabel: {
    fontSize: TYPOGRAPHY.size.xs,
    color: COLORS.textLight,
    marginBottom: 4,
  },
  statValue: {
    fontSize: TYPOGRAPHY.size.sm,
    fontWeight: TYPOGRAPHY.weights.bold,
    color: COLORS.white,
    flexShrink: 1,
    flexWrap: 'nowrap',
    textAlign: 'center',
  },
  explorerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
    paddingVertical: 10,
    backgroundColor: COLORS.darkerBackground,
    borderRadius: 8,
  },
  explorerButtonText: {
    color: COLORS.brandBlue,
    fontSize: TYPOGRAPHY.size.lg,
    fontWeight: TYPOGRAPHY.weights.semiBold,
    marginRight: 8,
  },
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  tagPill: {
    backgroundColor: COLORS.darkerBackground,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginRight: 8,
    marginBottom: 8,
  },
  tagText: {
    color: COLORS.brandBlue,
    fontSize: TYPOGRAPHY.size.xs,
  },
  attributesContainer: {
    marginTop: 16,
    backgroundColor: COLORS.lighterBackground,
    borderRadius: 12,
    padding: 16,
  },
  attributeItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderDarkColor,
  },
  attributeLabel: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textLight,
  },
  attributeValue: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.white,
    fontWeight: TYPOGRAPHY.weights.medium,
  },
  linkText: {
    color: COLORS.brandBlue,
  },
  statsSummaryContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: COLORS.lighterBackground,
    borderRadius: 12,
    padding: 16,
    marginVertical: 16,
  },
  positiveChange: {
    color: '#00C851',
  },
  negativeChange: {
    color: COLORS.errorRed,
  },
  marketMetricsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
    backgroundColor: COLORS.lighterBackground,
    borderRadius: 12,
    padding: 16,
  },
  marketMetricItem: {
    alignItems: 'center',
  },
  marketMetricLabel: {
    fontSize: TYPOGRAPHY.size.xs,
    color: COLORS.textLight,
    marginBottom: 4,
  },
  marketMetricValue: {
    fontSize: TYPOGRAPHY.size.lg,
    fontWeight: TYPOGRAPHY.weights.semiBold,
    color: COLORS.white,
  },
  coingeckoButton: {
    backgroundColor: '#8DC647',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 16,
  },
  coingeckoButtonText: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.size.sm,
    fontWeight: TYPOGRAPHY.weights.semiBold,
  },
  chartContainer: {
    height: 250,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
    backgroundColor: COLORS.lightBackground,
    borderRadius: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  chartEmptyText: {
    color: COLORS.greyMid,
    fontSize: TYPOGRAPHY.size.md,
  },
  marketplacesContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    marginBottom: 10,
  },
  marketplaceButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderRadius: 12,
    width: '48%',
  },
  marketplaceButtonText: {
    fontSize: TYPOGRAPHY.size.sm,
    fontWeight: TYPOGRAPHY.weights.semiBold,
    marginRight: 8,
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(12, 16, 26, 0.8)', // Using background color with transparency
  },
  loadingText: {
    fontSize: TYPOGRAPHY.size.xl,
    fontWeight: TYPOGRAPHY.weights.bold,
    color: COLORS.white,
    marginTop: 20,
  },
  collectionStatsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  statBox: {
    flexDirection: 'column',
    alignItems: 'center',
  },
  collectionStatLabel: {
    fontSize: TYPOGRAPHY.size.xs,
    color: COLORS.textLight,
    marginBottom: 4,
  },
  collectionStatValue: {
    fontSize: TYPOGRAPHY.size.sm,
    fontWeight: TYPOGRAPHY.weights.bold,
    color: COLORS.white,
  },
  statSubValue: {
    fontSize: TYPOGRAPHY.size.xs,
    color: COLORS.textLight,
  },
  noWrap: {
    flexShrink: 1,
    maxWidth: undefined,
    flexWrap: 'nowrap',
  },
  riskLoadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  riskLoadingText: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textLight,
    marginTop: 8,
  },
  riskErrorContainer: {
    padding: 20,
    alignItems: 'center',
  },
  riskErrorText: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.textLight,
    textAlign: 'center',
  },
  riskContainer: {
    backgroundColor: COLORS.lighterBackground,
    borderRadius: 12,
    padding: 16,
    marginTop: 8,
  },
  riskScoreContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  riskScoreBadge: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  riskScoreValue: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.size.lg,
    fontWeight: TYPOGRAPHY.weights.bold,
  },
  riskLabelContainer: {
    marginLeft: 12,
    flex: 1,
  },
  riskLabel: {
    fontSize: TYPOGRAPHY.size.lg,
    fontWeight: TYPOGRAPHY.weights.semiBold,
  },
  ruggedDescription: {
    fontSize: TYPOGRAPHY.size.xs,
    color: COLORS.errorRed,
    marginTop: 4,
  },
  riskDescription: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.white,
    marginBottom: 16,
    lineHeight: TYPOGRAPHY.lineHeight.sm,
  },
  riskFactorsTitle: {
    fontSize: TYPOGRAPHY.size.md,
    fontWeight: TYPOGRAPHY.weights.semiBold,
    color: COLORS.white,
    marginBottom: 12,
  },
  riskFactorItem: {
    backgroundColor: COLORS.darkerBackground,
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
  },
  riskFactorHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  riskFactorName: {
    fontSize: TYPOGRAPHY.size.sm,
    fontWeight: TYPOGRAPHY.weights.medium,
    color: COLORS.white,
    flex: 1,
  },
  riskLevelBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  riskLevelText: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.size.xs,
    fontWeight: TYPOGRAPHY.weights.bold,
  },
  riskFactorDescription: {
    fontSize: TYPOGRAPHY.size.xs,
    color: COLORS.textLight,
    lineHeight: TYPOGRAPHY.lineHeight.xs,
  },
  // Button container for swap and explorer buttons
  buttonsContainer: {
    flexDirection: 'row',
    marginTop: 16,
    gap: 8,
  },
  // Swap action button
  swapActionButton: {
    backgroundColor: COLORS.brandPrimary,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.brandPrimary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  swapActionButtonText: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.size.sm,
    fontWeight: TYPOGRAPHY.weights.semiBold,
    textAlign: 'center',
  },
  // Elegant swap button for top placement
  elegantSwapButton: {
    backgroundColor: COLORS.brandPrimary,
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 12,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 16,
    shadowColor: COLORS.brandPrimary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  swapButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  swapIconContainer: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  swapButtonTextContainer: {
    flex: 1,
    marginRight: 8,
  },
  swapButtonTitle: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.size.md,
    fontWeight: TYPOGRAPHY.weights.bold,
    marginBottom: 1,
  },
  swapButtonSubtitle: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: TYPOGRAPHY.size.xs,
    fontWeight: TYPOGRAPHY.weights.medium,
  },
  swapButtonArrow: {
    opacity: 0.8,
  },
});