import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    position: 'relative',
    width: 131,
    height: 161,
    backgroundColor: '#F6F7F9',
    borderWidth: 1,
    borderRadius: 12,
    overflow: 'hidden',
    borderColor: '#F2F2F2',
  },
  image: {
    top: 0,
  },
  profImg: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  imgBox: {
    overflow: 'hidden',
    position: 'absolute',
    top: 12,
    left: '50%',
    marginLeft: -32,
    width: 64,
    height: 64,
    borderWidth: 4,
    borderColor: 'white',
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  button: {
    position: 'absolute',
    bottom: 4,
    left: '50%',
    marginLeft: -59.5,
    backgroundColor: 'black',
    width: 119,
    height: 30,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: {
    fontSize: 12,
    fontWeight: '500',
    color: 'white',
    textAlign: 'center',
  },
  userInfoContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginLeft: -59.5,
    height: 37,
    width: 119,
  },
  usernameText: {
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  handleText: {
    fontSize: 12,
    fontWeight: '500',
    textAlign: 'center',
    color: '#ADADAD',
  },
});
