import { StyleSheet } from 'react-native';
import COLORS from '../../../../assets/colors';
import TYPOGRAPHY from '../../../../assets/typography';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: COLORS.darkerBackground,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '90%',
    paddingBottom: 30,
  },
  handleBar: {
    width: 40,
    height: 5,
    backgroundColor: COLORS.greyBorderdark,
    borderRadius: 3,
    alignSelf: 'center',
    marginVertical: 8,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderDarkColor,
    position: 'relative',
  },
  closeButton: {
    position: 'absolute',
    left: 20,
    padding: 5,
  },
  headerTitle: {
    fontSize: TYPOGRAPHY.size.lg,
    fontWeight: '600',
    fontFamily: TYPOGRAPHY.fontFamily,
    letterSpacing: TYPOGRAPHY.letterSpacing,
    color: COLORS.white,
  },
  content: {
    paddingHorizontal: 20,
  },
  typeBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 12,
    marginTop: 16,
  },
  iconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  typeInfo: {
    marginLeft: 12,
  },
  typeTitle: {
    fontSize: TYPOGRAPHY.size.md,
    fontWeight: '600',
    fontFamily: TYPOGRAPHY.fontFamily,
    letterSpacing: TYPOGRAPHY.letterSpacing,
    marginBottom: 4,
  },
  dateText: {
    fontSize: TYPOGRAPHY.size.xs,
    fontFamily: TYPOGRAPHY.fontFamily,
    letterSpacing: TYPOGRAPHY.letterSpacing,
    color: COLORS.accessoryDarkColor,
  },
  amountContainer: {
    alignItems: 'center',
    marginVertical: 24,
  },
  amountText: {
    fontSize: TYPOGRAPHY.size.xxl,
    fontWeight: '600',
    fontFamily: TYPOGRAPHY.fontFamily,
    letterSpacing: TYPOGRAPHY.letterSpacing,
  },
  swapContainer: {
    backgroundColor: COLORS.lightBackground,
    borderRadius: 12,
    padding: 16,
    marginVertical: 16,
  },
  swapRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  swapAmount: {
    alignItems: 'center',
    flex: 1,
  },
  swapValue: {
    fontSize: TYPOGRAPHY.size.md,
    fontWeight: '600',
    fontFamily: TYPOGRAPHY.fontFamily,
    letterSpacing: TYPOGRAPHY.letterSpacing,
    color: COLORS.white,
    marginBottom: 4,
  },
  swapLabel: {
    fontSize: TYPOGRAPHY.size.xs,
    fontFamily: TYPOGRAPHY.fontFamily,
    letterSpacing: TYPOGRAPHY.letterSpacing,
    color: COLORS.accessoryDarkColor,
  },
  swapArrow: {
    marginHorizontal: 8,
  },
  detailsSection: {
    marginVertical: 16,
  },
  sectionTitle: {
    fontSize: TYPOGRAPHY.size.lg,
    fontWeight: '600',
    fontFamily: TYPOGRAPHY.fontFamily,
    letterSpacing: TYPOGRAPHY.letterSpacing,
    color: COLORS.white,
    marginBottom: 12,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderDarkColor,
  },
  detailLabel: {
    fontSize: TYPOGRAPHY.size.sm,
    fontFamily: TYPOGRAPHY.fontFamily,
    letterSpacing: TYPOGRAPHY.letterSpacing,
    color: COLORS.accessoryDarkColor,
  },
  detailValue: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.white,
    fontWeight: '500',
    fontFamily: TYPOGRAPHY.fontFamily,
    letterSpacing: TYPOGRAPHY.letterSpacing,
  },
  signatureContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  copyButton: {
    marginLeft: 8,
    padding: 6,
  },
  solscanButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.lightBackground,
    paddingVertical: 12,
    borderRadius: 8,
    marginVertical: 16,
  },
  solscanIcon: {
    marginRight: 8,
  },
  solscanText: {
    color: COLORS.brandBlue,
    fontWeight: '600',
    fontSize: TYPOGRAPHY.size.sm,
    fontFamily: TYPOGRAPHY.fontFamily,
    letterSpacing: TYPOGRAPHY.letterSpacing,
  },
  instructionsContainer: {
    marginTop: 16,
    marginBottom: 24,
  },
  instructionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  toggleButton: {
    padding: 4,
  },
  toggleButtonText: {
    fontSize: TYPOGRAPHY.size.sm,
    color: COLORS.brandBlue,
    fontWeight: '500',
    fontFamily: TYPOGRAPHY.fontFamily,
    letterSpacing: TYPOGRAPHY.letterSpacing,
  },
  instructionsList: {
    backgroundColor: COLORS.lightBackground,
    borderRadius: 12,
    padding: 12,
  },
  instructionItem: {
    marginBottom: 12,
  },
  instructionProgram: {
    fontSize: TYPOGRAPHY.size.xs,
    fontWeight: '600',
    fontFamily: TYPOGRAPHY.fontFamily,
    letterSpacing: TYPOGRAPHY.letterSpacing,
    color: COLORS.greyMid,
    marginBottom: 4,
  },
  instructionData: {
    backgroundColor: COLORS.lighterBackground,
    padding: 8,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: COLORS.borderDarkColor,
  },
  instructionDataText: {
    fontSize: TYPOGRAPHY.size.xs,
    color: COLORS.greyMid,
    fontFamily: 'monospace',
  },
  directionLabel: {
    fontSize: TYPOGRAPHY.size.xs,
    color: COLORS.accessoryDarkColor,
    fontWeight: '500',
    fontFamily: TYPOGRAPHY.fontFamily,
    letterSpacing: TYPOGRAPHY.letterSpacing,
  },
  tooltip: {
    position: 'absolute',
    bottom: 30,
    right: 0,
    backgroundColor: 'rgba(0,0,0,0.75)',
    borderRadius: 6,
    padding: 8,
    zIndex: 1000,
    minWidth: 200,
    maxWidth: 280,
  },
  tooltipText: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.size.xs,
    textAlign: 'center',
    fontFamily: TYPOGRAPHY.fontFamily,
    letterSpacing: TYPOGRAPHY.letterSpacing,
  },
  tooltipArrow: {
    position: 'absolute',
    bottom: -8,
    right: 10,
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 8,
    borderRightWidth: 8,
    borderTopWidth: 8,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: 'rgba(0,0,0,0.75)',
  },
}); 